### ISSUE TITLE
Running on NixOs

### ISSUE THREAD

**Issue by Talia-12** [InioX/matugen#106]
This one I unfortunately don't understand. I've forked the repo, updated the flake.lock so it's using a correct rust version, and with that change it builds, but trying to run the program prints `error: unexpected argument found` if any option is given to it (e.g. `-h`). Using `rust-gcd` to step into it the problem is happening in the Cli struct, apparently in the code called by `#[derive(Parser)]`, but I couldn't figure out more than that. (I ran into this issue as a roadblock on an attempted PR to add custom_color support to the Nix module.)

**Comment by Talia-12** [comment]
Ah, nevermind, I think was running into "no good error message setup for an invalid argument" plus "dump-json only optionally installed". (dump-json being not-by-default installed is a problem for the nix module though, since it makes use of it and can't at that point request that feature compiled in, so to get it working would require setting that feature in the call to `buildRustPackage` in `default.nix`.)

**Comment by InioX** [comment]
I added the build flag into flake.nix and fixed a bug inside `dump_json`, I do not know if it builds though.

**Comment by Talia-12** [comment]
can confirm that the changes you made enable building and using the module on nix.
