### ISSUE TITLE
Option for Hyprland specific format

### ISSUE THREAD

**Issue by Dakota5488** [InioX/matugen#119]
Hyprland for doesnt use hex, hex_stripped or rgba, it seems to be using a mixture of rgba and hex_stripped being formatted like so: `rgba(33ccffee)`

i was wondering if it'd be possible to create a format specifically for hyprland, as using neither hex_stripped nor rgba functions correctly, though encasing hex_stripped in `rgb(<hex_stripped>)` does make hyprland read it correctly
![image](https://github.com/user-attachments/assets/432bdf75-d28c-4bbd-9cbc-142ce7729318)

**Comment by Sasikuttan2163** [comment]
If you want to have alpha you can just have it like this:

```
general {
    col.inactive_border = rgba({{colors.background.default.hex_stripped}}77)
    col.active_border = rgba({{colors.primary.default.hex_stripped}}44)
}
```

**Comment by InioX** [comment]
I'll add this to the wiki
