### ISSUE TITLE
matugen is dumping the colors.css correctly but not setting the wallpaper passed as path.

### ISSUE THREAD

**Issue by paridhi089** [InioX/matugen#122]
Sorry I accidentally posted it on matugen-themes instead.  closing it there and reopening it here

Here is my configuration [file](https://gitlab.com/paridhips/hyprdots/-/blob/matugen/.config/matugen/config.toml?ref_type=heads). 

Here is the [color scheme](https://gitlab.com/paridhips/hyprdots/-/blob/matugen/.config/waybar/colors.css?ref_type=heads) generated by matugen.

i ran 
``` matugen image ~/Pictures/wallpaper/11.jpg -m dark --show-colors ```

I tested with multiple wallpapers and all the color schemes were generated correctly. The only problem i am facing is that it is not replacing my current wallpaper. Here is my [hyprland config](https://gitlab.com/paridhips/hyprdots/-/blob/matugen/.config/hypr/hyprland.conf?ref_type=heads).

I also ran 
```
 matugen image ~/Pictures/wallpaper/13.jpg -m dark -d     
``` 

I got the following output

```        
ℹ Opening image in /home/quasar_paridhi/Pictures/wallpaper/13.jpg
ℹ Loaded 1 templates.
Trying to write the waybar template to /home/quasar_paridhi/hyprdots/.config/waybar/colors.css
✔ [1/1] Exported the waybar template to /home/quasar_paridhi/hyprdots/.config/waybar/colors.css

```
Am i missing something or doing something wrong?

**Comment by Axenide** [comment]
Just started using Matugen and found the same issue.

**Comment by InioX** [comment]
I only tested on windows for now and it works fine for me, I'll test it on linux tomorrow

**Comment by paridhi089** [comment]
I believe the path is not being passed to the swww. It thought there is some code in the background to take the path of the image when we run 
``` matugen image <path> ```
And pass it to swww

**Comment by paridhi089** [comment]
Issue #123 pointed out that some documentation is missing. I believe that the [config.wallpaper] syntax is wrong.

**Comment by Juhan280** [comment]
What version of matugen are you using?
Wallpaper is working fine in v2.4.0.
But the one from aur (v2.3.0) doesn't work

**Comment by Axenide** [comment]
Ah, that explains it. I'm using the AUR version.
