### ISSUE TITLE
AMOLED Dark mode

### ISSUE THREAD

**Issue by Harith163** [InioX/Matugen#2]
Hi!

it would be really cool there were an extra dark mode ala AMOLED black. Not sure where to start with that though.

**Comment by Harith163** [comment]
It would be cool if you could split the primary color into two component colors and make them secondary and tertiary. 

If that's not possible, I think background and surface is pretty cool!

**Comment by Harith163** [comment]
Also, thank you!

**Comment by InioX** [comment]
> It would be cool if you could split the primary color into two component colors and make them secondary and tertiary.

I'm sorry, but I don't understand what you mean by that. Could you please explain it a bit more?

**Comment by InioX** [comment]
Also, after trying the "pure black" mode on my Android, I should probably dim the other surface colors a bit to make them look similar.

**Comment by Harith163** [comment]
So, suppose that the primary family is a purple-ish, lavendar-ish color.

Secondary could be a blue and tertiary can be a red/pink.

There may be a sophistacted algorithm for this, but I was just thinking along the lines of 

#aa88ff ---> #aa4400 + #0044ff

basically, we see which color channel is the dimmest and split across that axis?

**Comment by InioX** [comment]
I hope i understand now, did you mean something like this? 
![](https://lh3.googleusercontent.com/1VEzJeGNEMYFspRMrdyVNxE0DNaAdSKdmKq677OqhjAvN3BSULi4rdIDf87d6cAWlBfsb9i3KjV193jUN8AkSu6f1lp2I8UpwU3BC8VZjEWY=s0)

If that's what you mean, you can use these colors already. The list of all the colors is right [here](https://github.com/InioX/Matugen#example-of-all-the-color-keywords).

**Comment by InioX** [comment]
So, I would shift the hue for the secondary/tertiary colors like this?

<img src="https://atelierlks.com/wp-content/uploads/2017/10/colorwheel-triadic-simple2.png" width="150"/>

**Comment by Harith163** [comment]
Yeah! The triadic palette takes colors evenly across the color wheel, while i was imagining something more like the adjacent scheme that you can play around with here. 

https://paletton.com/#uid=54H0L0kAarQnc-Zu6zgEqmCKJhf

There are other versions like complimentary and tetradic too. Since the monet palette is built around three colors, the triadic or adjacent palettes would be cool additions

**Comment by InioX** [comment]
The link you provided me really helped me understand, I could try adding that. Since the amoled mode was added though, I should close this issue. Please make another one for the different secondary/tertiary colors.
