### ISSUE TITLE
gtk-3.0 and 4.0

### ISSUE THREAD

**Issue by m4st3r-bl4ckb1rd** [InioX/Matugen#4]
hi...

first. this is a great project and i'm happy that i found it.
i managed to theme my hyprland, waybar, cava, kitty, astrovim, wofi and mako (notification daemon)

gut what i did not understand was the gtk theme.
tryed to figure it out also with your dotfiles (nixos tree).

it would be great if you could send an short tutorial something simular.
(also checked mitsugen)

Thanks,

**Comment by InioX** [comment]
Hi there! Thanks a lot for the kind words. I can't make a tutorial at the moment, but I could make one tomorrow if that's fine. Have you installed and applied the [adw-gtk3](https://github.com/lassekongo83/adw-gtk3) theme? Also, are GTK4 apps being themed or not?

**Comment by m4st3r-bl4ckb1rd** [comment]
don't hurry i have time ;)

yes i installed and applyed adw-gtk-dark and templated gtk.css/colors.css but the highlight color did not changed
thats why i asked for an tutorial. maybe i missed something.

**Comment by InioX** [comment]
Could you show the `gtk.css` and `colors.css` files in the `gtk-3.0` and `gtk-4.0` folders? You also have to close and reopen some apps for them to use the proper theme. If that doesn't work, try logging off and back in again. I remember it fixed my issue the first time I applied the theme, after that it changed without any problems. You could also try checking the current theme: 
```console
$ gsettings get org.gnome.desktop.interface gtk-theme
```

**Comment by m4st3r-bl4ckb1rd** [comment]
i use the same as your dotfiles.
and i got it to change but only if i close all gtk app... e.g.
i had nemo open changed the colors via mutagen and gtk accent_color was changed but it reflects first after closing all nemo windows and open a new one.

reload_gtk_theme in config.toml is set true

i thought that would change on the fly

**Comment by InioX** [comment]
Unfortunately the GTK theme for the app doesn't change unless you kill all instances of it on Wayland. If you're using X11, you can try following this [post](https://www.reddit.com/r/bspwm/comments/qm4p9r/how_to_change_the_gtk_without_killing_all/) for "hot reloading" using `xsettingsd`. 

I should probably add a section about this in the README.

**Comment by InioX** [comment]
Unfortunately the GTK theme for the app doesn't change unless you kill all instances of it on Wayland. If you're using X11, you can try following this [post](https://www.reddit.com/r/bspwm/comments/qm4p9r/how_to_change_the_gtk_without_killing_all/) for "hot reloading" using `xsettingsd`. 

I should probably add a section about this in the README.
