### ISSUE TITLE
Mode in config seems to be ignored

### ISSUE THREAD

**Issue by marcelohdez** [InioX/matugen#44]
I have a script which passes `--mode light` or dark depending on time of day, but i like my Waybar being always dark, so for the Waybar template i set `mode = "Dark"` in the Matugen config, but this seems to make no difference

**Comment by marcelohdez** [comment]
My hunch after a quick glance is that we generate colors in this function: https://github.com/InioX/matugen/blob/d2a268b46d6a387642f7b52f7fcf0b199e26c282/src/util/template.rs#L169
Which uses `default_scheme` which is only generated by the `args` in `main.rs`: https://github.com/InioX/matugen/blob/d2a268b46d6a387642f7b52f7fcf0b199e26c282/src/main.rs#L68-L70
But, we never read each template's `mode` when creating them, only the same colors variable as above: https://github.com/InioX/matugen/blob/d2a268b46d6a387642f7b52f7fcf0b199e26c282/src/util/template.rs#L226-L238
(But I may be dumb, let me know if I am doing something incorrectly)

**Comment by InioX** [comment]
Hi @marcelohdez! Sorry for the very delayed response. 

If you want the color to be always dark, you can specify the mode inside the keyword like this: 

```
{{colors.<keyword>.dark.<format>}}
```

As for not reading the mode from the template, I rewrote the template code a while ago and completely forgot about it. Implementing it back would require to generate the colors for every template inside the loop and I think specifying the mode inside the keyword is enough. I will rewrite the documentation and remove the mode from config.
