### ISSUE TITLE
Prefix does not work

### ISSUE THREAD

**Issue by n1ckisthereu** [InioX/matugen#47]
My config: File

[templates.kitty]
input_path = '~/.config/matugen/default/kitty.conf'
output_path = '~/.config/kitty/colors.conf'

[config]
reload_apps = true
set_wallpaper = false

[config.reload_apps_list]
kitty = true
gtk_theme = true

When generating new color scheme, the prefixes is not replaced, my final file:

cursor #f0f0f0
cursor_text_color #ffffff

@{surface}

i need use

{{colors.on_surface.default.hex}}

**Comment by InioX** [comment]
That's intended behavior since 1.0.0.
