### ISSUE TITLE
[FEATURE REQUEST] Additionaly output 8 basic terminal colors

### ISSUE THREAD

**Issue by junnunkarim** [InioX/matugen#53]
Would it be possible to output the 8 basic terminal colors (black, red, green, yellow, blue, magenta, cyan and white) based on the wallpaper alongside the normal output?

**Comment by InioX** [comment]
Hi, @junnunkarim !

I don't think I'm sure what you mean. How would the 8 static colors change based on wallpaper?

The only thing i can think of is harmonizing the colors like [this](https://m3.material.io/styles/color/advanced/adjust-existing-colors)?

**Comment by junnunkarim** [comment]
Hello @InioX !

I was thinking that just like how the primary, secondary and tertiary colors are generated, it would also be possible to generate those 8 colors. Sorry but I wasn't thinking deep enough. I now understand that a wallpaper might not contain all 8 colors which would create a significant issue.

Ater checking out what harmonizing colors mean, I think it might be the option that I would like to have.
But as far as I can understand, it would be necessary to first use a static set of 8 colors.
So how would you be dealing with this? How about taking those 8 colors as input alongside the wallpaper and output the harmonized colors? Or is there any better way?

**Comment by InioX** [comment]
I was thinking of just adding a field for `harmonized_colors` inside the config file. Something like this
```toml
[config]
# ...

[config.harmonized_colors]
green = "#00FF00"
red = "#FF0000"
blue = "#0000FF"
# ...
```

**Comment by InioX** [comment]
Sorry for the delay, I had some issues with my laptop. The colors seem a bit weird to me but everything should be implemented. Is this what you had in mind?

#### Configuration file
```toml
[config.colors_to_harmonize]
green = "#00FF00"
red = "#FF0000"
blue = "#0000FF"
```

#### Template file
![image](https://github.com/InioX/matugen/assets/81521595/66a92d66-997d-48f8-8db6-cfa0d5a749c4)

#### Output
![image](https://github.com/InioX/matugen/assets/81521595/068ef5d6-dde9-4587-b406-29dbbbf01965)

**Comment by junnunkarim** [comment]
No worries and Thank you!
Yes, this is what I would like to have. (although the colors do seem a little bit weird)
But if possible would you push the changes to a branch, so that I could test this feature out?

**Comment by InioX** [comment]
I forgot to push the changes, sorry about that. It is on the `dev` branch now.

**Comment by junnunkarim** [comment]
I have tested out and it's working perfectly! Thank You!
### Harmonized colors with generated colorscheme (terminal)
![Showcasing harmonized colors](https://github.com/InioX/matugen/assets/24603630/00af34d5-bbbb-424f-88c5-d351d6da1e59)

Would it be possible to output the harmonized colors with the json option?

**Comment by InioX** [comment]
I'm happy to see that it's working like it should!

I forgot about something **AGAIN**. I was gonna add it but then started working on filters... Sorry about that, I'll add it in a bit.

**Comment by junnunkarim** [comment]
Thank you so much for your kind words :-)

It okay, happens to me all the time.
I will wait for that feature to be implemented before closing this issue.

**Comment by junnunkarim** [comment]
Although harmonized colors were included in json but there seems to be an issue with the format it outputs in.
If I output using `hex`, it still outputs the harmonized colors in `rgb` format.

Here's the output -
```json
"harmonized_colors": {
    "blue": [
        255,
        135,
        165,
        143
    ],
    "cyan": [
        255,
        155,
        226,
        197
    ],
    "green": [
        255,
        211,
        179,
        0
    ],
    "magenta": [
        255,
        214,
        134,
        143
    ],
    "orange": [
        255,
        255,
        125,
        83
    ],
    "red": [
        255,
        252,
        71,
        65
    ],
    "yellow": [
        255,
        255,
        185,
        101
    ]
}
```

**Comment by InioX** [comment]
I'm starting to think I have dementia, I'll fix it.

**Comment by junnunkarim** [comment]
Sorry for the pressure 😅

**Comment by junnunkarim** [comment]
It's okay, I understand your issue. I will wait.
Good Luck getting your new pc!

**Comment by InioX** [comment]
Hi, sorry for the long wait.

Some complications happened with the pc, so I wanted to try if matugen builds on android.

When running `cargo install matugen` everything compiles fine but when trying to `cargo run` in the repository, it doesn't compile and throws an error. Tried searching for the error and I haven't seen anything like it so I dunno.

I guess i could try installing a linux distro inside termux and trying to compile matugen inside of it. But that seems like too much, maybe I should just wait.

The laptop is being fixed right now and I'm giving it a week until its done, maybe even sooner. Again, sorry for the wait but I can't really do anything right now.

**Comment by junnunkarim** [comment]
Thank you for letting me now.
But don't worry, there's no rush.

As for termux, I have encountered issues multiple times when compiling and running rust programs. So some time ago I just installed a proot distro and since then I can compile and run programs just fine. Issues still happen but a lot less than before. Although compiling takes quite some time, but atleast in proot I can use a native arm build of rust compiler rather than the patched one on termux.
You may want to try out [TermuxArch](https://github.com/TermuxArch/TermuxArch).

Again, there's no rush, take your time. I will wait.
