### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by keilmillerjr** [InioX/matugen#54]
Any chance of creating an AUR package? Thank you.

**Comment by InioX** [comment]
Hi,

I can try but I have no experience packaging on AUR.

**Comment by umop3plsdn** [comment]
the aur file is showing up "not found"

**Comment by InioX** [comment]
It now shows an error with sha256 mismatch probably because I had to force push the overwritten v2.2.0 tag to actually test the workflow.

I don't know if i should create a new release version to fix all of this?

**Comment by InioX** [comment]
Seems to install fine now.
