### ISSUE TITLE
Question: Is it possible to "lock-in" a color?

### ISSUE THREAD

**Issue by mkstowe** [InioX/matugen#67]
I'd like to generate a palette with some predefined colors. For example, have the primary and secondary colors locked-in, and generate the rest of the palette around those. Is this possible?

**Comment by InioX** [comment]
You mean definining a custom static color for primary and secondary, and generate the rest of the scheme based on the source color?

**Comment by mkstowe** [comment]
Either that or have the source color be the same as primary.

**Comment by InioX** [comment]
You can now overwrite colors by adding a color into `custom_colors`, naming it the same as the color you want to overwrite.

Example:

```toml
[config.custom_colors]
primary = "#00FF00"
```

When you use `{{ colors.primary.default.hex }}`, it will be the defined color.
