### ISSUE TITLE
Question:  Custom Keywords Not Working

### ISSUE THREAD

**Issue by CmrCrabs** [InioX/matugen#75]
I cant seem to get the custom keywords to work, as far as I can see this is how you are meant to do it per the wiki but maybe I am misunderstanding?

Matugen Config (it is written by nix so those ${} values are replaced):
```
    [config.custom_keywords.rounding]
    find = 'rounding'
    replace = '${rounding}'
   
    [config.custom_keywords.transparency]
    find = 'transparency'
    replace = '${transparency}'
```

Error Message:
```
Error: 
   0: TOML parse error at line 8, column 1
   0:   |
   0: 8 | [config.custom_keywords.rounding]
   0:   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   0: invalid type: map, expected a string
   0: 
```

Documentation for reference:
![image](https://github.com/InioX/matugen/assets/100045694/0eef1777-d7e3-4630-9e8b-80a90886467b)

Any help would be greatly appreciated

**Comment by CmrCrabs** [comment]
by making it so the keyword is different I get to a different error, but again I dont see why it wouldnt work

Relevant Config:
```
    [custom_keywords.rounding]
    find = 'rounding1'
    replace = '${rounding}'
   
    [custom_keywords.transparency]
    find = 'transparency1'
    replace = '${transparency}'
 ```
In template:
 ```
 $rounding = {{custom.rounding1}}
```

**Comment by InioX** [comment]
The usage has been changed to
```toml
[config.custom_keywords]
test = "aaaa"
```

**Comment by InioX** [comment]
Updated the wiki.

**Comment by CmrCrabs** [comment]
yep that worked, thank you. I'll close the issue
