### ISSUE TITLE
Make version check optional

### ISSUE THREAD

**Issue by Theaninova** [InioX/matugen#78]
The version check seems to take a rather substantial amount of the execution time, as well as being useless if the app is installed via the system package manager.

Imo the check should be opt-in, as it makes a network request that is not required for the app to function.

**Comment by InioX** [comment]
Would adding a config option for it that's disabled by default be fine?

**Comment by Theaninova** [comment]
I think a config option would be the best option, I'm not sure if you meant disabled by default as in turning off the check is off by default or turning on the check is disabled by default, I think either is fine though I'd advocate for the check being opt-in (so off by default) rather than opt out, or a build flag for the default state so it can be turned off when packaging for non-cargo targets.
