### ISSUE TITLE
Noob question: how do I make a template?

### ISSUE THREAD

**Issue by Dreuzz** [InioX/matugen#79]

**Comment by InioX** [comment]
https://github.com/InioX/matugen/wiki/Configuration#creating-templates

**Comment by Dreuzz** [comment]
I already saw that and spend 2 hours trying to understand it

**Comment by InioX** [comment]
I apologize. Does something like this [example](https://github.com/InioX/matugen/blob/main/example/colors.whatever-extension) help?

You could also take a look at the [template folder](https://github.com/InioX/dotfiles/tree/nixos/dotfiles/templates) from my dotfiles.

**Comment by Dreuzz** [comment]
This helped a lot but im still facing some issues:

'''
Errors parsing configuration


In file /home/dreuzzz/.config/kitty/current-theme.conf:
1:Invalid color name: {{colors.on_surface.default.hex}} in line: cursor {{colors.on_surface.default.hex}}

2:Invalid color name: {{colors.on_surface_variant.default.hex}} in line: cursor_text_color {{colors.on_surface_variant.default.hex}}

4:Invalid color name: {{colors.on_surface.default.hex}} in line: foreground            {{colors.on_surface.default.hex}}

5:Invalid color name: {{colors.surface.default.hex}} in line: background            {{colors.surface.default.hex}}

6:Invalid color name: {{colors.on_secondary.default.hex}} in line: selection_foreground  {{colors.on_secondary.default.hex}}

7:Invalid color name: {{colors.secondary_fixed_dim.default.hex}} in line: selection_background  {{colors.secondary_fixed_dim.default.hex}}

8:Invalid color name: {{colors.primary.default.hex}} in line: url_color             {{colors.primary.default.hex}}

28:Invalid color name: {{colors.primary.default.hex}} in line: color4  {{colors.primary.default.hex}}

Press Enter or Esc to exit
'''

**Comment by InioX** [comment]
It looks like you aren't using the generated file but the template instead.

**Comment by Dreuzz** [comment]
do you know I can fix this?

**Comment by InioX** [comment]
Run matugen, and use the `output_path` in the config as the path for your generated kitty configuration.
