### ISSUE TITLE
Integration with papirus-folders

### ISSUE THREAD

**Issue by Heus-Sueh** [InioX/matugen#83]
I'm almost reaching the perfect rice, but I didn't find an easy way to select the available colors of papirus-folders based on accent_color in matugen

https://github.com/PapirusDevelopmentTeam/papirus-folders

**Comment by InioX** [comment]
After a bit of thinking, I wanted to make this a bit more modular and not just lock it to the colors for papirus-folders.

I thought about adding something like this:
```toml
colors_to_compare = [
  { name = "white", color = "#ffffff" },
  { name = "black", color = "#000000" }
]
compare_against = "primary"
```

Matugen would loop over all the colors, compare them with the other color and output the closest one inside of the list by using the `--json` flag. You could then pipe it into something like `jq` and do stuff based on what the color is.

I'm not sure if this is the best way or the easiest one, if you have any other ideas feel free to share them.

**Comment by Heus-Sueh** [comment]
> After a bit of thinking, I wanted to make this a bit more flexible and not just lock it to the colors for papirus-folders.
> 
> I thought about adding something like this:
> 
> ```toml
> colors_to_compare = [
>   { name = "white", color = "#ffffff" },
>   { name = "black", color = "#000000" }
> ]
> compare_against = "primary"
> ```
> 
> Matugen would loop over all the colors, compare them with the other color and output the closest one inside of the list by using the `--json` flag. You could then pipe it into something like `jq` and do stuff based on what the color is.
> 
> I'm not sure if this is the best way or the easiest one, if you have any other ideas feel free to share them.

I think this flexibility is the correct path, and I want to suggest perhaps the concept of hook, like this:

```
[template.papirus-folders]
colors_to_compare = [
 { name = "white", color = "#ffffff" },
 { name = "black", color = "#000000" }
]
compare_against = "primary"
chosen_color = "result_of_compare"
hook = 'papirus-folders -C {chosen_color} --theme Papirus-Dark'
```

matugen already has this with gtk (when running matugen it will call the hook that will use gsettings to set adw-gtk), but it is harcoded just for him, maybe making this flexible for templates would be interesting, like this:

` { input_path = 'path', output_path = 'path', hook = 'sway reload' } `

I saw this hook concept in this program: https://github.com/Misterio77/flavours?tab=readme-ov-file#setup

**Comment by InioX** [comment]
I forgot to make them execute stuff, I'll fix it later. For now, here's an example for the hook:
```toml
[templates.name1]
input_path = "example/colors.whatever-extension"
output_path = "example/a/colors-generated.whatever-extension"
colors_to_compare = [
    { name = "black", color = "#000000" },
    { name = "red", color = "#ff0000" },
    { name = "maroon", color = "#800000" },
    { name = "yellow", color = "#ffff00" },
    { name = "olive", color = "#808000" },
    { name = "lime", color = "#00ff00" },
    { name = "green", color = "#008000" },
    { name = "aqua", color = "#00ffff" },
    { name = "teal", color = "#008080" },
    { name = "blue", color = "#0000ff" },
    { name = "navy", color = "#000080" },
    { name = "fuchsia", color = "#ff00ff" },
    { name = "purple", color = "#800080" },
]
compare_to = "#aefbd5"
hook = "source color {source_color}, source image {source_image}, compared color {compared_color}"
```

**Comment by Heus-Sueh** [comment]
In `compare_to`, can you put a variable, like in the previous example?

like that:
`compare_to = "{{colors.primary.default.hex}}"`

**Comment by InioX** [comment]
No but I'll make it do that if you want.

**Comment by Heus-Sueh** [comment]
> No but I'll make it do that if you want.

If there is no negative side, it might be interesting to implement

**Comment by InioX** [comment]
It executes now, so feel free to test stuff.

**Comment by Heus-Sueh** [comment]
In the case of papirus-folders I don't need an `input` or `output`, I just need the result of comparing all those variables and which one is closest to the generated color `colors.primary.default.hex`, so that I call the hook to start the command with the closest color

```
[templates.papirus-folders]
colors_to_compare = [
    { name = "adwaita", color = "#aacae8" },
    { name = "blue", color = "#7cabe2" },
    { name = "breeze", color = "#7fc4e9" },
    { name = "carmine", color = "#b54142" },
    { name = "darkcyan", color = "#72bbc4" },
    { name = "green", color = "#a1bf80" },
    { name = "indigo", color = "#838dca" },
    { name = "nordic", color = "#9db4cb" },
    { name = "palebrown", color = "#d6c9bd" },
    { name = "pink", color = "#ec87a9" },
    { name = "teal", color = "#159a80" },
    { name = "white", color = "#e4e4e4" },
    { name = "yellow", color = "#f3c863" },
    { name = "black", color = "#797979" },
    { name = "bluegray", color = "#869aa4" },
    { name = "brown", color = "#bda68e" },
    { name = "cyan", color = "#41c7d8" },
    { name = "deeporange", color = "#e98a68" },
    { name = "grey", color = "#a6a6a6" },
    { name = "magenta", color = "#d192e0" },
    { name = "orange", color = "#eba96a" },
    { name = "paleorange", color = "#ebd1a7" },
    { name = "red", color = "#e27c7c" },
    { name = "violet", color = "#9b7fcb" }
]
compare_to = "{{colors.primary.default.hex}}"
hook = "papirus-folders -C {closest_color} --theme Papirus-Dark"
```

Would it be a good idea to implement this, these "special" cases?

**Comment by InioX** [comment]
I already added the `{{ compared_color }}`, which is just like `{{ closest_color }}` you mentioned. I also wanted to add the same formatting for `hook` as in the templates, and I will also add the same formatting for `compare_to`.

**Comment by Heus-Sueh** [comment]
> I already added the `{{ compared_color }}`, which is just like `{{ closest_color }}` you mentioned. I also wanted to add the same formatting for `hook` as in the templates, and I will also add the same formatting for `compare_to`.

Okay, I was unsure about the name `compared_color`, sorry my English isn't very good

**Comment by InioX** [comment]
> > I already added the `{{ compared_color }}`, which is just like `{{ closest_color }}` you mentioned. I also wanted to add the same formatting for `hook` as in the templates, and I will also add the same formatting for `compare_to`.
> 
> Okay, I was unsure about the name `compared_color`, sorry my English isn't very good

I decided to rename it, `closest_color` seems better.

Also added formatting to `compare_to` as well, so you can now use all the color keywords inside it.

**Comment by Heus-Sueh** [comment]
https://github.com/InioX/matugen/assets/98482469/a4057720-682c-401d-af6c-7c5493cf15a2

**Comment by Heus-Sueh** [comment]
Testing here, in some wallpapers it gets it right, in others it refuses and chooses only the `black` color from the `papirus-folders`, even though a wallpaper has a lot of blue, it chooses `black`. 

here is a "log": 
https://privatebin.net/?d6d1d2d127729ad0#5tPASKCQSTQi3iXuNNnDn7pskwnR6ZJoGDjbyVdArMBM

**Comment by InioX** [comment]
Could you post the wallpapers this is happening with?

**Comment by Heus-Sueh** [comment]
> Could you post the wallpapers this is happening with?

![2023-08-14-11-00-18-cat](https://github.com/InioX/matugen/assets/98482469/34d5bd95-c824-4a56-91dc-b5b42eaa0eda)

**Comment by Heus-Sueh** [comment]
I will post others

**Comment by InioX** [comment]
> > Could you post the wallpapers this is happening with?
> 
> ![2023-08-14-11-00-18-cat](https://private-user-images.githubusercontent.com/98482469/344470295-34d5bd95-c824-4a56-91dc-b5b42eaa0eda.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NTg4NDUsIm5iZiI6MTcxOTc1ODU0NSwicGF0aCI6Ii85ODQ4MjQ2OS8zNDQ0NzAyOTUtMzRkNWJkOTUtYzgyNC00YTU2LTkxZGMtYjViNDJlYWEwZWRhLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDE0NDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2Y2JiNjA0M2EyMGViNjUyYzU0MDJiMmMyYTJlMWQxNDVjYjVhYzViYTRkMTU5ZTY4MmI1Yzg2ZmI2Yzg3YjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SSfVG1-Vn_UGTiOCsZ8-4RbHiqIVC8XYSB9Gud_S82I)

This image seems to work fine
![image](https://github.com/InioX/matugen/assets/81521595/cc5c8fb9-a4ed-45da-8171-d74043220bef)
![image](https://github.com/InioX/matugen/assets/81521595/4cacdbb5-d832-405a-a08f-204f6be4df7a)

**Comment by Heus-Sueh** [comment]
I was testing these colors which would be the colors of the papirus-folders folders that I got using the color picker, would it be better to use the template you provided?

```
colors_to_compare = [
    { name = "adwaita", color = "#93c0ea" },
    { name = "blue", color = "#5294e2" },
    { name = "breeze", color = "#57b8ec" },
    { name = "carmine", color = "#a30002" },
    { name = "darkcyan", color = "#45abb7" },
    { name = "green", color = "#a1bf80" },
    { name = "indigo", color = "#838dca" },
    { name = "nordic", color = "#9db4cb" },
    { name = "palebrown", color = "#d6c9bd" },
    { name = "pink", color = "#ec87a9" },
    { name = "teal", color = "#159a80" },
    { name = "white", color = "#e4e4e4" },
    { name = "yellow", color = "#f3c863" },
    { name = "black", color = "#797979" },
    { name = "bluegray", color = "#869aa4" },
    { name = "brown", color = "#bda68e" },
    { name = "cyan", color = "#41c7d8" },
    { name = "deeporange", color = "#e98a68" },
    { name = "grey", color = "#a6a6a6" },
    { name = "magenta", color = "#d192e0" },
    { name = "orange", color = "#eba96a" },
    { name = "paleorange", color = "#ebd1a7" },
    { name = "red", color = "#e27c7c" },
    { name = "violet", color = "#9b7fcb" }
]
```

**Comment by InioX** [comment]
I would use the papirus-folders colors and maybe add some middle colors, while naming it the same as the color you want to get.
