### ISSUE TITLE
Is there a way to generate light and dark colors without running matugen twice?

### ISSUE THREAD

**Issue by Heus-Sueh** [InioX/matugen#84]
I generally use the dark theme, but I wanted to see what the themes would look like in light mode, but there is no way to generate two files, one for dark mode and one for light mode, just overwrite

**Comment by InioX** [comment]
Why not just use `{{ colors.<color>.default.<format> }}` and then switch between dark/light mode with the `-m` flag?

**Comment by Heus-Sueh** [comment]
I'm just stupid lol, I tested the light mode but it wasn't very good, maybe I configured it too much based on the dark mode
