### ISSUE TITLE
[Nix] Currently not building

### ISSUE THREAD

**Issue by CmrCrabs** [InioX/matugen#85]
Using the flake, is not building.

Error:
![image](https://github.com/InioX/matugen/assets/100045694/0072e8dd-d70a-4e89-9cf6-713e20ba60af)

**Comment by CmrCrabs** [comment]
also doesnt build for rev edb6caede2c1a23a6a95af43088619fd3ff539aa ? 

may be an error on my end then?

**Comment by InioX** [comment]
I was testing the code on windows and it ignored the linux specific functions, so you got the error but I didn't. Should be fixed now.

**Comment by CmrCrabs** [comment]
Yep, builds now, thanks. Closing
