### ISSUE TITLE
[Feature Request] run_after function accepts variables

### ISSUE THREAD

**Issue by Heus-Sueh** [InioX/matugen#91]
I was thinking about this type of case, do you find the idea interesting?

swww example
```
[config]
reload_apps = true
set_wallpaper = true
wallpaper_tool = 'swww'
swww_options = [
    "--transition-type",
    "center",
    "--transition-fps",
    "60",
    "--transition-duration",
    "3"
    "--transition-bezier",
    "0.4,0.2,0.4,1.0"
]
run_after = [
    [ "{wallpaper_tool} {image} {swww_options}" ],
]
```
Thinking about it, the example is bad since matugen already does this, but adding a section for custom variables could be interesting

example:

```
[Custom-Variables]
custom_wallpaper_tool = "wpaperd"
custom_wallpaper_options [ ... ]
```
that way matugen wouldn't have to support new wallpaper tools

then these variables could be used in `hooks` and `run_after`

```
[config]
run_after = [ " {custom_wallpaper_tool} {image} {custom_wallpaper_options} " ] 
```

**Comment by InioX** [comment]
`run_after` has been removed if you look at the [config](https://github.com/InioX/matugen/blob/250809841ed4133ced82d78e3d46e2425f86694f/src/util/config.rs#L50) and [template](https://github.com/InioX/matugen/blob/250809841ed4133ced82d78e3d46e2425f86694f/src/util/template.rs#L50) structs, even in the wiki (still, it needs some updates). 

To use custom variables inside hooks you could add them to `config.custom_keywords` like this
```toml
[config.custom_keywords]
wallpaper_tool= "swaybg"
```

and then inside a hook you would do
```
hook = "{{ custom.wallpaper_tool }} -i {{ image }}"
```

**Comment by InioX** [comment]
Enabled discussions
